version: "3.7"

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: serv/.env
    ports:
      - "5432:5432"

volumes:
  data:
